### ISSUE TITLE
Gives internal server error when username or password is incorrect

### ISSUE THREAD

**Issue by abhishek-compro** [jowilf/starlette-admin-demo#2]
https://github.com/jowilf/starlette-admin-demo/blob/main/app/sqla/auth.py#L61

```
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette_admin/contrib/sqla/middleware.py", line 29, in dispatch
    response = await call_next(request)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette_admin/auth.py", line 165, in dispatch
    return await call_next(request)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette_admin/base.py", line 333, in _render_login
    return self.templates.TemplateResponse(
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/templating.py", line 112, in TemplateResponse
    return _TemplateResponse(
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/templating.py", line 38, in __init__
    content = template.render(context)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette_admin/templates/login.html", line 1, in top-level template code
    {% extends "layout.html" %} {% block header %}{% endblock %} {% block sidebar
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette_admin/templates/layout.html", line 3, in top-level template code
    {% set current_user = (request | get_admin_user) %}
  File "/home/user/repos/project-demo/./admin/auth.py", line 60, in get_admin_user
    user = request.state.user  # Retrieve current user
  File "/home/user/.cache/pypoetry/virtualenvs/project-demo-cde5jiA-py3.10/lib/python3.10/site-packages/starlette/datastructures.py", line 705, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'user'
```

**Comment by jowilf** [comment]
Thank you for reporting this. The bug is in starlette-admin itself and it's now fixed in 0.5.5
